---
language: c # vala
compiler:
  - gcc
  - clang
env:
  - VALAC=valac-0.20
  - VALAC=valac-0.18
before_install:
  - sudo add-apt-repository -y ppa:vala-team/ppa
  - sudo apt-get update -qq
  - sudo apt-get install -qq ${VALAC}
  - sudo apt-get install -qq libgirepository1.0-dev gobject-introspection gir1.2-glib-2.0
  - sudo apt-get install -qq libgee-dev gir1.2-gee-1.0
before_script:
  - ./waf configure
  - ./waf build
script: ./waf test
